AppCoder/urls.py
from django import views
from django.urls import path
from .views import Login_a_Pagina, RegistroPagina, UsuarioEdicion, CambioClave, InicioView ,galeriaComedia, ComediaDetalle, ComediaUpdate, PeliculasCreacion,ComediaDelete, GaleriaTerror, TerrorDetalle, TerrorUpdate,TerrorDelete, GaleriaAccion,AccionDetalle,AccionrUpdate,AccionDelete,GaleriaRomanticas,RomanticasDetalle,RomanticasUpdate, RomanticasDelete, GaleriaSuspenso, SuspensoDetalle, SuspensoUpdate,SuspensoDelete, GaleriaOtras,OtrasDetalle, OtrasUpdate, OtrasDelete, ComentarioPagina, AvatarFormulario, agregaravatar
from django.contrib.auth.views import  LogoutView
from . import views


urlpatterns = [
    #urls de usuario y registro y login.
    path('', InicioView.as_view(), name='inicio'),
    path('login/', Login_a_Pagina.as_view(), name='login'),
    path('registro/', RegistroPagina.as_view(), name='registro'),
    path('logout/', LogoutView.as_view(template_name='AppCoder/logout.html'), name='logout'),
    path('edicionPerfil/', UsuarioEdicion.as_view(), name='editar_perfil'),
    path('ClavesCambio/', CambioClave.as_view(), name='cambiar_password'),
    path('ClavesExitoso/' , views.password_exitoso, name='password_exitoso'),
    path('Avatar/' , views.agregaravatar, name='Avatar'),
    
    
    #asesorios de galeria
    
    path('galeriaComedia/', galeriaComedia.as_view(), name='comedia'),
    path('GaleriaTerror/', GaleriaTerror.as_view(), name='terror'),
    path('GaleriaAccion/', GaleriaAccion.as_view(), name='accion'),
    path('GaleriaRomanticas/', GaleriaRomanticas.as_view(), name='romanticas'),
    path('GaleriaSuspenso/', GaleriaSuspenso.as_view(), name='suspenso'),
    path('GaleriaOtras/', GaleriaOtras.as_view(), name='otraspeliculas'),
   
    
    
    #detalles de peliculas
    
    path('comediaDetalle/<int:pk>/', ComediaDetalle.as_view(), name='comedias'),
    path('TerrorDetalle/<int:pk>/', TerrorDetalle.as_view(), name='terror'),
    path('accionDetalle/<int:pk>/', AccionDetalle.as_view(), name='accion'),
    path('RomanticasDetalle/<int:pk>/', RomanticasDetalle.as_view(), name='romanticas'),
    path('SuspensoDetalle/<int:pk>/', SuspensoDetalle.as_view(), name='suspenso'),
    path('OtrasDetalle/<int:pk>/', OtrasDetalle.as_view(), name='otraspeliculas'),
    
    
    #Temas de Edicion
    
    path('comediaEdicion/<int:pk>/', ComediaUpdate.as_view(), name='comedia_editar'),
    path('terrorEdicion/<int:pk>/', TerrorUpdate.as_view(), name='terror_editar'),
    path('accionEdicion/<int:pk>/', AccionrUpdate.as_view(), name='accion_editar'),
    path('RomanticasEdicion/<int:pk>/', RomanticasUpdate.as_view(), name='romanticas_editar'),
    path('SuspensoUpdate/<int:pk>/', SuspensoUpdate.as_view(), name='suspenso_editar'),
    path('OtrasUpdate/<int:pk>/', OtrasUpdate.as_view(), name='suspenso_editar'),
    
    
    #Eliminacion
    
    path('comediaBorrado/<int:pk>/', ComediaDelete.as_view(), name='comedia_eliminar'),
    path('terrorBorrado/<int:pk>/', TerrorDelete.as_view(), name='terror_eliminar'),
    path('accionBorrado/<int:pk>/', AccionDelete.as_view(), name='accion_eliminar'),
    path('romanticasBorrado/<int:pk>/', RomanticasDelete.as_view(), name='romanticas_eliminar'),
    path('suspensoBorrado/<int:pk>/', SuspensoDelete.as_view(), name='suspenso_eliminar'),
    path('OtrasBorrado/<int:pk>/', OtrasDelete.as_view(), name='otras_eliminar'),
    
    
    
    #Creacion de peliculas
    
    path('PeliculaCreacion/', PeliculasCreacion.as_view(), name='nuevo'),
    
    
    #Crear Comentario por pelicula 
    
    path('comediaDetalle/<int:pk>/comentario/', ComentarioPagina.as_view(), name='comentario'),
    path('terrorDetalle/<int:pk>/comentario/', ComentarioPagina.as_view(), name='comentario'),
    path('accionDetalle/<int:pk>/comentario/', ComentarioPagina.as_view(), name='comentario'),
    path('romanticasDetalle/<int:pk>/comentario/', ComentarioPagina.as_view(), name='comentario'),
    path('suspensoDetalle/<int:pk>/comentario/', ComentarioPagina.as_view(), name='comentario'),
    path('otrasDetalle/<int:pk>/comentario/', ComentarioPagina.as_view(), name='comentario'),
    
    #algo sobre mi y mi vida
    path('algosobremi/', views.about, name='conoceme'),

     
]

ProyectoCoder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppCoder.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppCoder/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Peliculas(models.Model):
    peliculas_a_Seleccion = (('comedias','Comedias'),('terror', 'Terror'),('accion','Accion'),
                             ('romanticas','Romanticas'),('suspenso','Suspenso')
                            ,('otras', 'Otras'),)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    nombre = models.CharField(max_length=100)
    genero = models.CharField(max_length=15, choices=peliculas_a_Seleccion, default='Seleccione aqui el tipo')
    region = models.CharField(max_length=30)
    tipo = models.CharField(max_length=30)
    descripcion = models.TextField(null=True, blank=True)
    year = models.IntegerField() 
    duracion = models.DecimalField(max_digits=10, decimal_places=2)
    anio_extreno = models.DateTimeField(auto_now_add=True)
    telefonoContacto = models.IntegerField()
    emailContacto = models.EmailField()
    imagenPeliculas = models.ImageField(null=True, blank=True, upload_to="imagenes/")

    class Meta:
        ordering = ['usuario', '-anio_extreno']

    def __str__(self):
        return self.nombre

class Comentario(models.Model):
    comentario = models.ForeignKey(Peliculas, related_name='comentarios', on_delete=models.CASCADE, null=True)
    nombre = models.CharField(max_length=40)
    mensaje = models.TextField(null=True, blank=True)
    fechaComentario = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-fechaComentario']

    def __str__(self):
        return '%s - %s' % (self.nombre, self.comentario)
    
class Avatar(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="avatares", null=True, blank=True)
    

AppCoder/views.py
from django.views.generic import TemplateView, ListView, DetailView, UpdateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView 
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from .models import Peliculas, Comentario, Avatar
from .forms import ActualizacionPeliculas, FormularioCambioPassword, FormularioEdicion, FormularioNuevoPeliculas, FormularioRegistroUsuario, FormularioComentario, AvatarFormulario

#Agregar un avatar a su perfil

def agregaravatar(request):
    
    if request.method=="POST":
        form = AvatarFormulario(request.post, request.FILES)
        
        if form.is_valid():
            
            usuarioactual = User.objects.get(username=request.user)
            
            avatar = Avatar(usuario=usuarioactual, imagen=form.cleaned_data["imagen"])
            
            avatar.seve()
            
            return render(request, 'AppCoder/inicio.html')
        else:
            form = AvatarFormulario
            
        return render(request,"AppCoder/avatar.html", {"formulario":form})



# Create your views here.

class InicioView(LoginRequiredMixin, TemplateView):
    template_name = 'AppCoder/Inicio.html'
    
class Login_a_Pagina(LoginView):
    template_name = 'AppCoder/login.html'
    fields = '__all__'
    redirect_autheticated_user = True
    success_url = reverse_lazy('inicio')

    def get_success_url(self):
        return reverse_lazy('inicio')
    
class RegistroPagina(FormView):
    template_name = 'AppCoder/registrar.html'
    form_class = FormularioRegistroUsuario
    redirect_autheticated_user = True
    success_url = reverse_lazy('inicio')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegistroPagina, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('incio')
        return super(RegistroPagina, self).get(*args, **kwargs)

class UsuarioEdicion(UpdateView):
    form_class = FormularioEdicion
    template_name= 'AppCoder/edicionPerfil.html'
    success_url = reverse_lazy('inicio')

    def get_object(self):
        return self.request.user

class CambioClave(PasswordChangeView):
    form_class = FormularioCambioPassword
    template_name = 'AppCoder/clavesCambio.html'
    success_url = reverse_lazy('password_exitoso')

def password_exitoso(request):
    return render(request, 'AppCoder/clavesExitoso.html', {})


#galeria de peliculas = Comedia

class galeriaComedia(LoginRequiredMixin, ListView):
    context_object_name = 'comedias'
    queryset = Peliculas.objects.filter(genero__startswith='comedias')
    template_name = 'AppCoder/galeriaComedia.html'
    login_url = '/login/'
 
class ComediaDetalle(LoginRequiredMixin, DetailView):
    model = Peliculas
    context_object_name = 'comedias' 
    template_name = 'AppCoder/ComediaDetalle.html'

class ComediaUpdate(LoginRequiredMixin, UpdateView):
    model = Peliculas
    form_class = ActualizacionPeliculas
    success_url = reverse_lazy('comedias')
    context_object_name = 'comedias'
    template_name = 'AppCoder/ComediaEdicion.html'

class ComediaDelete(LoginRequiredMixin, DeleteView):
    model = Peliculas
    success_url = reverse_lazy('comedias')
    context_object_name = 'comedias'
    template_name = 'AppCoder/comediasBorrado.html'

#galeria de peliculas = terror

class GaleriaTerror(LoginRequiredMixin, ListView):
    context_object_name = 'terror'
    queryset = Peliculas.objects.filter(genero__startswith='terror')
    template_name = 'AppCoder/GaleriaTerror.html'
    login_url = '/login/'
    
class TerrorDetalle(LoginRequiredMixin, DetailView):
    model = Peliculas
    context_object_name = 'terror'
    template_name = 'AppCoder/terrorDetalle.html'
    
    
class TerrorUpdate(LoginRequiredMixin, UpdateView):
    model = Peliculas
    form_class = ActualizacionPeliculas
    success_url = reverse_lazy('terror')
    context_object_name = 'terror'
    template_name = 'AppCoder/TerrorUpdate.html'

class TerrorDelete(LoginRequiredMixin, DeleteView):
    model = Peliculas
    success_url = reverse_lazy('terror')
    context_object_name = 'terror'
    template_name = 'AppCoder/terrorBorrado.html'
    
    
#galeria de peliculas = Accion
  
class GaleriaAccion(LoginRequiredMixin, ListView):
    context_object_name = 'accion'
    queryset = Peliculas.objects.filter(genero__startswith='accion')
    template_name = 'AppCoder/GaleriaAccion.html'
    login_url = '/login/'  
    
class AccionDetalle(LoginRequiredMixin, DetailView):
    model = Peliculas
    context_object_name = 'accion'
    template_name = 'AppCoder/AccionDetalle.html'
    
class AccionrUpdate(LoginRequiredMixin, UpdateView):
    model = Peliculas
    form_class = ActualizacionPeliculas
    success_url = reverse_lazy('accion')
    context_object_name = 'accion'
    template_name = 'AppCoder/AccionrUpdate.html'
    
    
class AccionDelete(LoginRequiredMixin, DeleteView):
    model = Peliculas
    success_url = reverse_lazy('accion')
    context_object_name = 'accion'
    template_name = 'AppCoder/accionBorrado.html'
    
    

#galeria de peliculas = romanticas
    
class GaleriaRomanticas(LoginRequiredMixin, ListView):
    context_object_name = 'romanticas'
    queryset = Peliculas.objects.filter(genero__startswith='romanticas')
    template_name = 'AppCoder/GaleriaRomanticas.html'
    login_url = '/login/'   
    
class RomanticasDetalle(LoginRequiredMixin, DetailView):
    model = Peliculas
    context_object_name = 'romanticas'
    template_name = 'AppCoder/RomanticasDetalle.html'

class RomanticasUpdate(LoginRequiredMixin, UpdateView):
    model = Peliculas
    form_class = ActualizacionPeliculas
    success_url = reverse_lazy('romanticas')
    context_object_name = 'romanticas'
    template_name = 'AppCoder/RomanticasrUpdate.html'
    

class RomanticasDelete(LoginRequiredMixin, DeleteView):
    model = Peliculas
    success_url = reverse_lazy('romanticas')
    context_object_name = 'romanticas'
    template_name = 'AppCoder/RomanticasBorrado.html'
    
    
#galeria de peliculas = suspenso

class GaleriaSuspenso(LoginRequiredMixin, ListView):
    context_object_name = 'suspenso'
    queryset = Peliculas.objects.filter(genero__startswith='suspenso')
    template_name = 'AppCoder/GaleriaSuspenso.html'
    login_url = '/login/'   
    
class SuspensoDetalle(LoginRequiredMixin, DetailView):
    model = Peliculas
    context_object_name = 'suspenso'
    template_name = 'AppCoder/SuspensoDetalle.html'

class SuspensoUpdate(LoginRequiredMixin, UpdateView):
    model = Peliculas
    form_class = ActualizacionPeliculas
    success_url = reverse_lazy('suspenso')
    context_object_name = 'suspenso'
    template_name = 'AppCoder/SuspensoUpdate.html'
    

class SuspensoDelete(LoginRequiredMixin, DeleteView):
    model = Peliculas
    success_url = reverse_lazy('suspenso')
    context_object_name = 'suspenso'
    template_name = 'AppCoder/suspensoBorrado.html'
    

#galeria de peliculas = otras   

class GaleriaOtras(LoginRequiredMixin, ListView):
    context_object_name = 'otras'
    queryset = Peliculas.objects.filter(genero__startswith='otras')
    template_name = 'AppCoder/GaleriaOtras.html'
    login_url = '/login/'   

class OtrasDetalle(LoginRequiredMixin, DetailView):
    model = Peliculas
    context_object_name = 'otras'
    template_name = 'AppCoder/otrasDetalle.html'
    
class OtrasUpdate(LoginRequiredMixin, UpdateView):
    model = Peliculas
    form_class = ActualizacionPeliculas
    success_url = reverse_lazy('otras')
    context_object_name = 'otras'
    template_name = 'AppCoder/OtrasUpdate.html'
    
class OtrasDelete(LoginRequiredMixin, DeleteView):
    model = Peliculas
    success_url = reverse_lazy('otras')
    context_object_name = 'otras'
    template_name = 'AppCoder/otrasBorrado.html'   


# CREACION PELICULAS

class PeliculasCreacion(LoginRequiredMixin, CreateView):
    model = Peliculas
    form_class = FormularioNuevoPeliculas
    success_url = reverse_lazy('inicio')
    template_name = 'AppCoder/PeliculasCreacion.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(PeliculasCreacion, self).form_valid(form)

#COMENTARIOS

class ComentarioPagina(LoginRequiredMixin, CreateView):
    model = Comentario
    form_class = FormularioComentario
    template_name = 'AppCoder/comentario.html'
    success_url = reverse_lazy('inicio')

    def form_valid(self, form):
        form.instance.comentario_id = self.kwargs['pk']
        return super(ComentarioPagina, self).form_valid(form)

# ACERCA DE MI

def about(request):
    return render(request, 'AppCoder/acercademi.html', {})

AppCoder/templates/AppCoder/AccionrUpdate.html
{% extends 'AppCoder/inicio.html' %}

{% block content %}

<br>
<br>

{% if user.id == accion.usuario.id %}
<div class="container">

    <h4>Editar pelicula de Accion</h4>
    
</div>

<div class="container">
    <div class="form-group">
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>    
</div>
<br>
{% else %}
<div class="container">
<h4>No tienes acceso a esta pagina!</h4>
</div>
{% endif %}
{% endblock %}

AppCoder/templates/AppCoder/ComediaDetalle.html
{% extends 'AppCoder/inicio.html' %}

{% block content %}

<br>
<br>

<div class="container">

<p><h4>{{comedia.nombre}}</h4></p>

{% if comedia.imagenPeliculas %}
    <p><img src="{{comedias.imagenPeliculas.url}}" alt=""></p>
{% endif %}
<p>Marca: {{comedia.region }}</p>
<p>Modelo: {{comedia.tipo}}</p>
<p>Descripción: {{comedia.descripcion}}</p>
<p>Año: {{comedia.duracion}}</p>
<p>Precio(US$): {{comedia.year}}</p>
<p>Teléfono de Contacto: {{comedia.telefonoContacto}}</p>
<p>Email de Contacto: {{comedia.emailContacto}}</p>

</div>
<br>
<div class="container">
    <h4>Comentarios...</h4>
    <br>
    <div class="container">
    {% if not comedia.comentarios.all %}
        No han comentado esta pelicula
    {% else %}
        {% for comentario in comedia.comentarios.all %}
        <p><strong>{{comentario.nombre}}</strong></p>
        <p>{{comentario.mensaje}}</p>
        <p><small>{{comentario.fechaComentario}}</small></p>
        <hr>
        {% endfor %}
    {% endif %}
    <a href="{% url 'comentario' comedia.pk %}">Agrega un Comentario</a>
    </div>
</div>
<br>
{% endblock %}

AppCoder/templates/AppCoder/GaleriaRomanticas.html
{% extends 'AppCoder/inicio.html' %}

{% block content %}

<br>
<br>
<div class="container text-center">
    <h1>Sesion de Pelis de romances/Amor</h1>
</div>

<br>

<div class="container text-center">
    <div class="row">
            {% for romanticas in romanticas %}
            <div class="col-sm-6 align-items-center">
                <div class="card-body">
                <img src="{{romanticas.imagenPeliculas.url}}" class="" width="300px">
                {{romanticas.nombre}}
                <a href="{% url 'romanticas' romanticas.id %}"><i class="bi bi-eye"></i></a>
                {% if user.id == romanticas.usuario.id %}
                <a href="{% url 'romanticas' romanticas.id %}"><i class="bi bi-pencil-fill"></i></a>
                <a href="{% url 'romanticas' romanticas.id %}"><i class="bi bi-trash text-danger"></i></a>
                <br>
                <br>
                <br>
                <br>
                {% endif %}
                </div>
            </div>
            {% endfor %}
    </div>
</div>
{% endblock %}

AppCoder/templates/AppCoder/clavesExitoso.html
{% extends 'AppCoder/inicio.html' %}

{% block content %}

<br>
<div>
    <h1>Su contraseña ha sido cambiada correctamente</h1>
</div>
<br>
{% endblock %}

AppCoder/templates/AppCoder/inicio.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
      
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Galeria de peliculas</title>
        <link rel="icon" type="image/x-icon" href="{% static 'AppCoder/assets/favicon.ico'%}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Tinos:ital,wght@0,400;0,700;1,400;1,700&amp;display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&amp;display=swap" rel="stylesheet" />
        
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'AppCoder/css/styles.css'%}" rel="stylesheet" />
</head>
<body>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark py-4 fixed-top">
            <div class="container">
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
                      <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navmenu">
                    <ul class="navbar-nav mr-auto">
                      <li class="nav-item">
                        <h3> <a class="nav-link" href="{% url 'inicio' %}"><span class="text-primary">INICIO</span></a></h3>
                      </li>
                      
                      <li class="nav-item">
                        <h3><a class="nav-link" href="{% url 'comedia' %}">Comedias</a></h3>
                      </li>

                      <li class="nav-item">
                        <h3><a class="nav-link" href="{% url 'terror' %}">Terror</a></h3>
                      </li>

                                            
                      <li class="nav-item">
                        <h3><a class="nav-link" href="{% url 'accion' %}">Accion</a></h3>
                      </li>

                      <li class="nav-item">
                        <h3><a class="nav-link" href="{% url 'romanticas' %}">Romanticas</a></h3>
                      </li>

                      <li class="nav-item">
                        <h3><a class="nav-link" href="{% url 'suspenso' %}">Suspenso</a></h3>
                      </li>

                      <li class="nav-item">
                        <h3><a class="nav-link" href="{% url 'otraspeliculas' %}">Otraspelis</a></h3>
                      </li>
                      <li class="nav-item">
                    <h3><a class="nav-link" href="{% url 'conoceme' %}">!Conocenos!</a></h3>
                      </li>
                      </div>
                      <div class="container"></div>
                      <div class="container"></div>
                      <div class="container"></div>
                    <div class="container"></div>
                    <div class="container"></div>
                    {% if request.user.is_authenticated %}
                    <div class="container">
                        <li class="nav-item">
                          <h2><span class="text-light"> Sesion: <strong>{{request.user.first_name}}</strong>!</span></h2>

                         {% with user.avatar_set.first  as  miAvatar %}
                          
                          {% if miAvatar  %}

                          <img src="{{miAvatar.imagen.url}}" alt="No se encontro imagen" style="max-width: 90px;">
                          
                          {% endif %}
                          
                          {% endwith %} 

                        </li>
                        </div>
                    <div class="container">
                    <li class="nav-item">
                        
                    </li>
                    </div>
                    <div class="container">
                    <li class="nav-item">
                        <h3><a class="nav-link" href="{% url 'editar_perfil' %}"><span class="text-primary">Perfil</span></a></h3>
                    </li>
                    </div>
                    <div class="container">
                        <li class="nav-item">
                            <h3><a class="nav-link" href="{% url 'Avatar' %}"><span class="text-primary">Avatar</span></a></h3>
                        </li>
                        </div>
                    <div class="container">
                    <li class="nav-item">
                        <h3><a class="nav-link" href="{% url 'logout' %}"><span class="text-primary">Salir!</span></a></h3>
                    </li>
                    </div>
                    {% else %}
                    <div class="container">
                    <li class="nav-item">
                        <h3><a class="nav-link" href="{% url 'login' %}"><span class="text-primary">Login</span></a></h3>
                    </li>
                    </div>
                    <div class="container">
                    <li class="nav-item">
                        <h3><a class="nav-link" href="{% url 'registro' %}"><span class="text-primary">Registrate</span></a></h3>
                    </li> 
                    </div>         
                    {% endif %}
                </ul>
                </div>    
            </div>     
            </nav>
        
        <!-- Background Video-->
        <video class="bg-video" playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop"><source src="{% static 'AppCoder/assets/mp4/pelis.mp4' %}" type="video/mp4" /></video>
        <!-- Masthead-->

        <div class="masthead">
        
            <div class="masthead-content text-white">
                <div class="container-fluid px-4 px-lg-0">

                    <h1 class="fst-italic lh-1 mb-4">Bienvenido a nuestra Galeria de Peliculas</h1>
     {% block content %}
     <!-- parte de carga -->
   
        <section id="home" class="text-dark p-5 p-lg-0 pt-lg-5 text-center text-sm-start">
          <div class="container text-center">
            <div class="">
                <div>
                    <h3><span class="text-primary">Ayudanos actualizar nuestra galeria, !!!Sube tus Peliculas favoritas aqui!!!</span></h3>
                </div>
        </section>
        
            <section class="p-5 p-lg-0 pt-lg-5 text-center text-sm-start">
              <div class="container">
                  <div class="">
                      <div class="text-center">
                          <p class="lead my-4">

                          </p>
                          <a href="{% url 'nuevo' %}"><button type="submit" class="btn btn-primary">Agregalo acá</button></a>
                      </div>
                  </div>
              </div>
          </section>               
            <br>
            <br>

        {% endblock %} 
                    <p class="mb-5">Con solo con tu registro y inicio de sesion podras subir tu peliculas que quieras</p>

                    
                    <form id="contactForm" data-sb-form-api-token="API_TOKEN">

                        <div class="row input-group-newsletter">
                        </div>


                        <div class="d-none" id="submitSuccessMessage">
                            <div class="text-center mb-3 mt-2">
                                <div class="fw-bolder">Form submission successful!</div>
                                To activate this form, sign up at
                                <br />
                                <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
        <!-- Social Icons-->
        <!-- For more icon options, visit https://fontawesome.com/icons?d=gallery&p=2&s=brands-->
        <div class="social-icons">
            <div class="d-flex flex-row flex-lg-column justify-content-center align-items-center h-100 mt-3 mt-lg-0">
                <a class="btn btn-dark m-4" href="#!"><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-dark m-4" href="#!"><i class="fab fa-instagram"></i></a>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        

        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        <a class="btn btn-primary btn-xl rounded-pill mt-5" href="#scroll">Learn More</a>
        

    </body>
   
</html>